### ISSUE TITLE
Supplement for Limitations page

### ISSUE THREAD

**Issue by Frederisk** [FizzerWL/Cs2hx#10]
## Generic classes limitation

For generic classes with static methods which used common type parameters, for example:

```cs
// Class:
public static class MyClass<T, TR> {
    public static T[] Foo(int number, Object o=null) {
        return new T[number] ;
    }
}

// Usage:
String[] r = MyClass<String, Double>.Foo(1);
```

This will result in what appears to be problematic output:

```hx
// Class:
class MyClass<T, TR> {
    public static function Foo(number:Int, o:Dynamic = null):Array<T> {
/* <Error: "Unknown identifier : T">-------------------------------^ */
        return [  ];
    }
    public function new() {
    }
}

// Usage:
var r:Array<String> = consoleapp.MyClass.Foo(1);
```

But Cs2hx does not prompt any errors.

## `typeof`

`typeof` is not available in most cases, except for a few methods of `Enum`. The exception message will appear:

```plain
System.Exception: typeof is not supported unless part of Enum.Parse or Enum.GetValues
```

**Comment by FizzerWL** [comment]
Thanks for the feedback!

I added the typeof limitation to the page.  For the first one I do agree that you found a limitation and it deserves to be on this page, but my understanding of Haxe's generic system is pretty poor so I'm not sure how to describe exactly what the limitation is.  Without knowing how to exactly describe it I won't add it page just yet.
