### ISSUE TITLE
 error CS5001: Program does not contain a static 'Main' method

### ISSUE THREAD

**Issue by travisbrownjohn** [FizzerWL/Cs2hx#3]
I get an error even when trying to convert a trivial, almost empty ConsoleApp project.  Any help is appreciated!

[ConsoleApp1.zip](https://github.com/FizzerWL/Cs2hx/files/3418616/ConsoleApp1.zip)

---> (Inner Exception #0) System.Exception: Build failed. 2 errors:
  warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
  error CS5001: Program does not contain a static 'Main' method suitable for an entry point

**Comment by FizzerWL** [comment]
It looks like you might be running into this bug?  https://github.com/dotnet/roslyn/issues/26029  Try using the resolution steps in that bug.

I tested your project on my computer and it worked fine for me, so there's no problem with the project.  Here was the command I used and output:

```
Cs2hx.exe /sln:h:\temp\ConsoleApp1\ConsoleApp1.sln
C# to haXe Converter
See http://www.codeplex.com/cs2hx for full info and documentation.


Converting project ConsoleApp1...
Building...
Parsing...
Parsed in 00:00:00.3686085. Writing out haxe...
Haxe written out in 00:00:00.5753615
Built in 00:00:01.4564070
Finished project ConsoleApp1 in 00:00:01.7606262
```

And here's the code it output:

```package consoleapp1;
using StringTools;
import system.*;
import anonymoustypes.*;

class Program
{
    static function Main(args:Array<String>):Void
    {
        system.Console.WriteLine("API:");
    }
    public function new()
    {
    }
}
```
